List<String> city = [
  "Adilpur : عادل پور",
  "Ahmadpur East : احمد پور ایسٹ",
  "Alipur : علی پور",
  "Arifwala : عارف والا",
  "Attock : اٹک",
  "Badah : بادہ",
  "Badin : بدین",
  "Bagarji : باگر جی",
  "Bahawalnagar : بہاولنگر",
  "Bahawalpur : بہاولپور",
  "Bakshshapur : بخشاپور",
  "Bandhi : بندھی",
  "Barkhan : برخان",
  "Bela : بیلا",
  "Berani : بیرانی",
  "Bhag : بھاگ",
  "Bhakkar : بھکر",
  "Bhalwal : بھلوال",
  "Bhan : بھان",
  "Bhera : بھیرہ",
  "Bhiria City : بھیریا شہر",
  "Bhiria Road : بھیریا روڈ",
  "Bhit Shah : بھٹ شاہ",
  "Bozdar : بوزدار",
  "Bulri : بلری",
  "Burewala : بورے والا",
  "Chak : چک",
  "Chakwal : چکوال",
  "Chaman : چمن",
  "Chambar : چمبر",
  "Chichawatni : چیچہ وطنی",
  "Chiniot : چنیوٹ",
  "Chishtian Mandi : چشتیاں منڈی",
  "Chitkan : چٹکان",
  "Chohar Jamali : چوہڑ جمالی",
  "Chor : کور",
  "Dadu : دادو",
  "Daharki : ڈہرکی",
  "Dalbandin : دالبندین",
  "Daro : ڈارو",
  "Darya Khan : دریا خان",
  "Darya Khan Mari : دریا خان ماڑی",
  "Daska : ڈسکہ",
  "Daulatpur : دولت پور",
  "Daur : داور",
  "Dera Allah Yar : ڈیرہ اللہ یار",
  "Dera Bugti : ڈیرہ بگٹی",
  "Dera Ghazi Khan : ڈیرہ غازی خان",
  "Dera Murad Jamali : ڈیرہ مراد جمالی",
  "Dhadar : دادر",
  "Dhoronaro : دھورونارو",
  "Digri : ڈیجی",
  "Dina : دینا",
  "Dinga : ڈنگا",
  "Dipalpur : دیپالپور",
  "Diplo : ڈپلو",
  "Dokri : ڈاکری",
  "Duki : ڈکی",
  "Faisalabad : فیصل آباد",
  "Faqirabad : فقیر آباد",
  "Fateh Jang : فتح جنگ",
  "Gaddani : گڈانی",
  "Gambat : گمبٹ",
  "Garello : گاریلو",
  "Garhi Khairo : گڑھی خیرو",
  "Garhi Yasin : گڑھی یاسین",
  "Ghakar : گھاکر",
  "Gharo : گھارو",
  "Ghauspur : غوث پور",
  "Ghotki : گھوٹکی",
  "Gojra : گوجرہ",
  "Golarchi : گولارچی",
  "Guddu : گڈو",
  "Gujar Khan : گوجر خان",
  "Gujranwala : گوجرانوالہ",
  "Gujrat : گجرات",
  "Gulistan-E-Jauhar : گلستان جوہر",
  "Gwadar : گوادر",
  "Hafizabad : حافظ آباد",
  "Hala : ہالا",
  "Harnai : ہرنائی",
  "Hasilpur : حاصل پور",
  "Haveli : حویلی",
  "Hingorja : ہنگورجا",
  "Hub : حب",
  "Hyderabad : حیدرآباد",
  "Islamkot : اسلام کوٹ",
  "Jacobabad : جیکب آباد",
  "Jalalpur Jattan : جلالپور جٹاں",
  "Jam Nawaz Ali : جام نواز علی",
  "Jam Sahib : جام صاحب",
  "Jampur : جام پور",
  "Jaranwala : جڑانوالہ",
  "Jati : جٹی",
  "Jauharabad : جوہرآباد",
  "Jhang : جھنگ",
  "Jhelum : جہلم",
  "Jhol : جھول",
  "Jhudo : جھڈو",
  "Jiwani : جیوانی",
  "Johi : جوہی",
  "Kadhan : کدھن",
  "Kalabagh : کالاباغ",
  "Kalat : قلات",
  "Kamalia : کمالیہ",
  "Kambar : قمبر",
  "Kamoke : کاموکے",
  "Kandhra : کنڈرا",
  "Kandiari : کنڈیاری",
  "Kandiaro : کینڈیارو",
  "Karachi : کراچی",
  "Karampur : کرم پور",
  "Kario Ghanwar : کیریو غنوار",
  "Karoondi : کارونڈی",
  "Karor Lal Esan : کرور لال عیسن",
  "Kashmor : کشمیر",
  "Kasur : قصور",
  "Kazi Ahmad : قاضی احمد",
  "Keti Bandar : کیٹی بندر",
  "Khadro : کھڈرو",
  "Khairpur : خیرپور",
  "Khairpur Nathan Shah : ناتھن شاہ",
  "Khandh Kot : کھنڈ کوٹ",
  "Khanewal : خانیوال",
  "Khanpur : خانپور",
  "Khanpur : خانپور",
  "Kharan : خاران",
  "Kharian : کھاریاں",
  "Khipro : کھپرو",
  "Khoski : کھوسکی",
  "Khuhra : کھرہ",
  "Khuzdar : خضدار",
  "Khyber : خیبر",
  "Kohlu : کوہلو",
  "Kot Diji : کوٹ ڈیجی",
  "Kot Ghulam Mohammad : کوٹ غلام محمد",
  "Kotri : کوٹری",
  "Kumb : کمب",
  "Kunri : کنری",
  "Lahore : لاہور",
  "Lakhi : لکھی",
  "Lalamusa : لالاموسا",
  "Larkana : لاڑکانہ",
  "Lodhran : لودھراں",
  "Loralai : لورالائی",
  "Mach : مچ",
  "Madeji : میڈجی",
  "Mailsi : میلسی",
  "Malakwal : ملکوال",
  "Mandi Bahauddin : منڈی بہاؤالدین",
  "Mastung : مستونگ",
  "Matiari : مٹیاری",
  "Matli : ماتلی",
  "Mehar : مہر",
  "Mehrabpur : محراب پور",
  "Mianwali : میانوالی",
  "Miro Khan : میرو خان",
  "Mirpur Bathoro : میرپور باتھورو",
  "Mirpur Khas : میرپور خاص",
  "Mirpur Mathelo : میرپور میتھیلو",
  "Mirpur Sakro : میرپور ساکرو",
  "Mirwah : میرواہ",
  "Mithi : مٹھی",
  "Moro : مورو",
  "Multan : ملتان",
  "Muridke : مریدکے",
  "Murree : مری",
  "Muzaffargarh : مظفر گڑھ",
  "Nabisar : نبیسر",
  "Nankana Sahib : ننکانہ صاحب",
  "Narowal : نارووال",
  "Nasarpur : نصرپور",
  "Nasirabad : نصیر آباد",
  "Naudero : نوڈیرو",
  "Naukot : نوکوٹ",
  "Naushahro Firoz : نوشہرو فیروز",
  "Nawabshah : نواب شاہ",
  "Noorpur Thal : نور پور تھل",
  "Nowshera Virkan : نوشہرہ ورکان",
  "Nushki : نوشکی",
  "Oderolal Station : اوڈرولال اسٹیشن",
  "Okara : اوکاڑہ",
  "Ormara : اورمارا",
  "Pacca Chang : پیکا چانگ",
  "Padidan : پیڈیڈن",
  "Pakpattan : پاکپتن",
  "Pano Aqil : پنو عاقل",
  "Pasni : پسنی",
  "Pasrur : پسرور",
  "Pattoki : پتوکی",
  "Perumal : پیرومل",
  "Phalia : پھالیہ",
  "Phularwan : پھولروان",
  "Phulji : پھلجی",
  "Pind Dadan Khan : پنڈ دادن خان",
  "Pindi Bhattian : پنڈی بھٹیاں",
  "Pindi Gheb : پنڈی گھیب",
  "Pirjo Goth : پیرجو گوٹھ",
  "Piryaloi : پیریالوئی",
  "Pishin : پشین",
  "Pithoro : پیتھورو",
  "Qadirabad : قادر آباد",
  "Qadirpur Ran : قادر پور ران",
  "Qila Disar Singh : قلعہ دیسار سنگھ",
  "Qila Sobha Singh : قلعہ سوبھا سنگھ",
  "Quaidabad : قائد آباد",
  "Quetta : کوئٹہ",
  "Rabwah : ربوہ",
  "Radhan : رادھن",
  "Rahim Yar Khan : رحیم یار خان",
  "Raiwind : رائے ونڈ",
  "Raja Jang : راجہ جنگ",
  "Rajanpur : راجن پور",
  "Rajo Khanani : راجو خانانی",
  "Ranipur : رانی پور",
  "Ratodero : رتوڈیرو",
  "Rawalpindi : راولپنڈی",
  "Renala Khurd : رینالہ خورد",
  "Rohri : روہڑی",
  "Rojhan : روجھان",
  "Rustam : رستم",
  "Saddar Gogera : صدر گوگیرہ",
  "Sadiqabad : صادق آباد",
  "Saeedabad : سعید آباد",
  "Safdarabad : صفدر آباد",
  "Sahiwal : ساہیوال",
  "Sakrand : سکرینڈ",
  "Samaro : سمارو",
  "Samasatta : سماسٹا",
  "Sambrial : سمبریل",
  "Sammundri : سمندری",
  "Sangala Hill : سانگالہ ہل",
  "Sanghar : سانگھڑ",
  "Sanjwal : سنجوال",
  "Sann : سان",
  "Sarai Alamgir : سرائے عالمگیر",
  "Sargodha : سرگودھا",
  "Sarhari : سرہاری",
  "Sehwan : سہون",
  "Setharja : سیٹارجا",
  "Shadiwal : شادیوال",
  "Shah Dipalli : شاہ دیپلی",
  "Shahdadkot : شہدادکوٹ",
  "Shahdadpur : شہدادپور",
  "Shahkot : شاہکوٹ",
  "Shahpur Chakar : شاہ پور چاکر",
  "Shahpur City : شاہ پور سٹی",
  "Shahpur Jahania : شاہ پور جہانیا",
  "Shahpur Saddar : شاہ پور صدر",
  "Shakargarh : شکر گڑھ",
  "Sharqpur : شرقپور",
  "Shehr Sultan : شہر سلطان",
  "Sheikhupura : شیخوپورہ",
  "Shekhupura : شیخوپورہ",
  "Shikarpur : شکارپور",
  "Shujaabad : شجاع آباد",
  "Sialkot : سیالکوٹ",
  "Sibi : سبی",
  "Sillanwali : سلیانوالی",
  "Sinjhoro : سنجھوڑو",
  "Sita Road : سیتا روڈ",
  "Sobhodero : سوبھوڈیرو",
  "Sodhra : سودھرا",
  "Sohawa : سوہاوا",
  "Sohbatpur : سہبت پور",
  "Sujawal : سجاول",
  "Sukheke : سکھیکے",
  "Sukkur : سکھر",
  "Surab : سوراب",
  "Talagang : تلہ گنگ",
  "Talhar : تلہار",
  "Tandlianwala : تاندلیانوالہ",
  "Tando Adam : ٹنڈو آدم",
  "Tando Allah Yar : ٹنڈو اللہ یار",
  "Tando Bagho : ٹنڈو باگو",
  "Tando Ghulam Ali : ٹنڈو غلام علی",
  "Tando Jam : ٹنڈو جام",
  "Tando Jan Mohammad : ٹنڈو جان محمد",
  "Tando Mitha Khan : ٹنڈو مٹھا خان",
  "Tando Muhammad Khan : ٹنڈو محمد خان",
  "Tangwani : تنگوانی",
  "Taunsa : تونسا",
  "Taxila : ٹیکسلا",
  "Thano Bula Khan : تھانو بولا خان",
  "Thari Mirwah : تھری میرواہ",
  "Tharushah : تاروشاہ",
  "Thatta : ٹھٹا",
  "Ther I : وہیں میں",
  "Ther I Mohabat : وہیں میں محبت",
  "Thul : تھول",
  "Tibba Sultanpur : ٹبہ سلطان پور",
  "Toba Tek Singh : ٹوبہ ٹیک سنگھ",
  "Tulamba : ٹلمبا",
  "Turbat : تربت",
  "Ubauro : یوبورو",
  "Uch : اچ",
  "Umarkot : عمرکوٹ",
  "Usta Muhammad : استاد محمد",
  "Uthal : اتھل",
  "Wadh : ودھ",
  "Wah : واہ",
  "Warah : وارہ",
  "Warburton : واربرٹن",
  "Wazirabad : وزیر آباد",
  "Winder : ونڈر",
  "Yazman : یزمان",
  "Zafarwal : ظفروال",
  "Zahir Pir : ظاہر پیر",
  "Zehri : زہری",
  "Zhob : ژوب",
  "Ziarat : زیارت",
];
